# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "public static"
email: "kmc7468@naver.com"
description: >- # this means to ignore newlines until "baseurl:"
    프로그래밍, 특히 C++와 관련된 게시물을 자주 업로드 하는 한 학생의 블로그입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kmc7468.github.io" # the base hostname & protocol for your site, e.g. http://example.com

repository: "https://github.com/kmc7468/kmc7468.github.io"
footer_message: "(C) 2018. kmc7468 All rights reserved."
categories_korean:
    all: "전체"
    notice: "공지사항"
subsites_korean:
    cppground: "C++마당"

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/